### ISSUE TITLE
Can it use a specific config settings for recollindex?

### ISSUE THREAD

**Issue by stardiviner** [alraban/org-recoll#4]
Hi, @alraban , I like your package!

I found the default `recollindex` command use system default config file in `/usr/share/recoll/recoll.conf`. It has `topdir=~` setting. I think `org-recoll` don't need to index the whole user home directory. I personally suggest `org-recoll` use a config to passed to `recollindex` command. About how to pass this config file to command, I'm still thinking, do you have any idea?

**Comment by alraban** [comment]
It only uses the recoll.conf in /usr/share/recoll.conf if you:
a) haven't put your own recoll.conf in ~/.recoll/recoll.conf and
b) have't customized the variable "org-recoll-index-invocation" to use a custom configuration file 

You can easily add a config file of your choice by adding "-c path/to/config/file" to org-recoll-index-invocation, which is what the documentation for that variable suggests:

```
(defcustom org-recoll-index-invocation "recollindex"
  "This is the shell command called by ORG-RECOLL-UPDATE-INDEX.
Modify this if your recoll configuration file is not in the
standard location.  Note: do not add an & as the function already
backgrounds the process by default"
  :group 'org-recoll
  :type 'string)
```

So you can easily substitute your own config file by either: putting it in the standard location (~/.recoll/recoll.conf), or customizing org-recoll-index-invocation to use a different path to your recoll.conf.
