### ISSUE TITLE
Active project?

### ISSUE THREAD

**Issue by AtomicNess123** [alraban/org-recoll#9]
Hi, is this project maintained? What is the different with e.g., helm-recoll or counsel-recoll? Thanks!

**Comment by alraban** [comment]
It's maintained, but I'm not actively developing any new features.  I use it regularly, and it currently works as expected.  If folks identify bugs I work to fix them.  Pull requests are also welcome, but sometimes need additional discussion.

As for differences, I tried to address this in the README: "helm-recoll exists, but it has a very different interface and also requires switching to helm. org-recoll is intended to provide a stand-alone, easy to use solution, which is also easy to integrate into an existing org-mode workflow."  Basically, I wanted a method that was completion-backend-agnostic and gave an experience that was more "search engine-like", similar to what you see in the recoll application.

**Comment by AtomicNess123** [comment]
Thanks. Does org-recoll accept specific indexes and how to indicate them?

**Comment by alraban** [comment]
org-recoll handles everything through shell calls out to the recoll program and does not engage with the index directly, so it will use whatever configuration and index that a shell call to recoll -t uses.  However, recoll permits specifying alternate configs on the command line using the -c flag, and the shell invocation that org-recoll uses is stored in a documented variable (org-recoll-command-invocation) that you can customize to point at a different recoll configuration and index. 

So there's no native support for index switching other than by customizing org-recoll-command-invocation to point at a different recoll config.

**Comment by AtomicNess123** [comment]
Thanks, that's ok. One can create a switch via customized simple function.

**Comment by AtomicNess123** [comment]
Hi, coming back to this, to always use a customized index, would this be the right syntax (not sure whether to use `defcustom` or `setq`).

`(setq org-recoll-command-invocation "recoll -c ~/.recoll_mydatabase")`

**Comment by alraban** [comment]
So you can use setq, but I'd recommend you include the other flags that are part of the default value of org-recoll-command-invocation or things will not work correctly (i.e. you need to pass the -t flag to avoid recoll starting up the GUI, and you want the -A flag to avoid breaking the parsing, etc.).  One other "gotcha" is that the -c flag expects you to pass the path to your configuration directory not a database file (although that may just be what you named your config directory?).  

So you'd want something like:
`(setq org-recoll-command-invocation "recoll -t -A -c /path/to/your/recoll/config/directory")`

**Comment by AtomicNess123** [comment]
Thanks, 
So it would be like:
`  (setq org-recoll-command-invocation "recoll -c ~/. recoll_mydatabase -t -A")`

This works.
I'm confused as to what the config directory is.
I have a default `~/.recoll` directory, but then the user can create index directories.
So I have several, one of them is  `~/.recoll_mydatabase` (which contains index of specific folders).

So I I guess I would point to a different index depending on my searching needs. Is this the most efficient approach?

Thanks!

**Comment by alraban** [comment]
I don't personally use multiple databases, so I can't advise on the most efficient approach, but if it works, it works :-)
